# Generated by Django 6.0.5 on 2026-05-23 23:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0002_alter_downloadticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadticket',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
